### ISSUE TITLE
Missing varable

### ISSUE THREAD

**Issue by Squid-Bomb** [ansible-lockdown/RHEL8-STIG#146]
#within the RHEL8-STIG-2.6.0\tasks\LE_audit_setup.yml src variable is missing
- name: copy audit binary
  copy:
      src: "{{copy_goss_from_path}}"

**Comment by uk-bolly** [comment]
hi @Squid-Bomb 

Thank you for takin the time to raise this issue. Could you please confirm the following.
Branch/release that you are using i can see that this is resolved in devel branch and a dummy entry has been added.
We are due to release soon into main, we need to ensure devel is working as expected.

Many thanks

uk-bolly

**Comment by georgenalen** [comment]
@Squid-Bomb,
 Yeah the branch would be good to know. I just checked both devel and main, both have the var in defaults/main.yml. 

-George

**Comment by uk-bolly** [comment]
hi @Squid-Bomb 

Just wondering you have any update on this issue that has been raised or if this is now resolved?

thanks

uk-bolly
