### ISSUE TITLE
Update the playbook to support the new and updated requirements in V1R12

### ISSUE THREAD

**Issue by aaronlippold** [ansible-lockdown/RHEL8-STIG#246]
## Feature Request or Enhancement

Update the playbook to support the new and updated requirements in V1R12

**Comment by uk-bolly** [comment]
hi @aaronlippold 

Thank you for raising this issue, We have had to change our release schedule and the way it works (below is a copy of the announcement). 
In short though that version is written and released to the subscribers. 

## Why are we changing?
Due to the number of repositories now under maintenance we have to introduce a way to release whilst adhering to our client commitments. We’ve always had to prioritize subscribers requests when working on this project. Which means sometimes some of the excellent community work takes longer to be committed than we would like. In order for us to maintain a level of release quality, we will be changing the release structure.

## What’s the plan?
We will aim to be releasing benchmark specific updates to the Community 90 days after they have been released to the Private (subscriber) community. This should enable us to keep to our aim to update within 2 weeks for release updates to existing benchmarks (new benchmarks often take a lot longer). Issue/Bug fixes will still go into the Public releases as they are now, it is only benchmark specific updates that are delayed. 

## How do I get this early release access?
You can become subscribers by following the links below this message, which allows you to sign up immediately or schedule a call to better go over what these options are.

### Links
[Lockdown Enterprise](https://www.lockdownenterprise.com/)

[Automation Counselor](https://www.mindpointgroup.com/cybersecurity-products/automation-counselor)

[Purchase Directly](https://www.lockdownenterprise.com/pricing)

**Comment by aaronlippold** [comment]
Are you still accepting PRs?

I’d be interesting in chatting about these changes as it may affect my work
streams.

I have to chatted with the team in over a year so it would be good to sync
up again.

--------
Aaron Lippold

***@***.***

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'

**Comment by uk-bolly** [comment]
hi @aaronlippold 

We are indeed still accepting PRs for the released versions here, we do have the private branch for subscribers where they are also able to raise PRs with priority fixes, prior to the community release.
Hope that explains things a little better?

Many thanks

uk-bolly

**Comment by uk-bolly** [comment]
hi @aaronlippold 

I believe this issue has been addressed and merged?
I will close this, but feel free to reopen if you are still experiencing this problem.
Maybe easier to pick up a chat on discord if you like?

https://www.lockdownenterprise.com/discord

many thanks

uk-bolly

**Comment by aaronlippold** [comment]
Hi, I will check it out and put it through the Pipeline.

I’d be more than happy to chat over discord, as rhel9 is next in line. 👍

--------
Aaron Lippold

***@***.***

260-255-4779

twitter/aim/yahoo,etc.
'aaronlippold'
