### ISSUE TITLE
Blacklisted module names should be lowercase

### ISSUE THREAD

**Issue by danbarr** [ansible-lockdown/RHEL8-STIG#62]
**Describe the Issue**
The ATM, CAN, SCTP, and TIPC kernel module blacklist entries are entered into /etc/modprobe.d/blacklist.conf in uppercase, causing SCAP scan to fail on RHEL-08-040021, RHEL-08-040022, RHEL-08-040023, RHEL-08-040024.

**Expected Behavior**
Module names in /etc/modprobe.d/blacklist.conf should be in lowercase.

**Actual Behavior**
SCAP scan fails on these four controls because it's looking for the module names atm, can, sctp, and tipc in lowercase.

**Control(s) Affected**
RHEL-08-040021
RHEL-08-040022
RHEL-08-040023
RHEL-08-040024

**Environment (please complete the following information):**
 - Ansible Version: 2.9.27
 - Host Python Version: 3.6.8
 - Role version: 2.3.0

**Possible Solution**
Will submit a PR

**Comment by uk-bolly** [comment]
Hi @danbarr 

Thank you again for taking the time to highlight issue so that we may continually improve this role. While the stig is followed to the letter, we are agreeing that this is the case and this should be lower case.
We are looking at a new release and will be sure to add this solution into the new release.

Thanks as always for your time.

uk-bolly

**Comment by uk-bolly** [comment]
Hi @danbarr 

These should now be in place in the latest devel release (which is also a stig update(where they have also changed the documentation to be lowercase)).
I will close this issue in the next week unless you have any questions?

Thanks as always for you feedback and support.

uk-bolly

**Comment by danbarr** [comment]
Looks good, thanks!
